<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312213155 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, contributors_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58562B477E3C61F9 ON board (owner_id)');
        $this->addSql('CREATE INDEX IDX_58562B47120460D1 ON board (contributors_id)');
        $this->addSql('CREATE TABLE "column" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D53877EE7EC5785 ON "column" (board_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, txt_color VARCHAR(20) NOT NULL, bg_color VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_order INT NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, title TEXT NOT NULL, content TEXT DEFAULT NULL, is_completed BOOLEAN NOT NULL, board_column_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25CA372FE ON task (board_column_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_527EDB25B03A8386 ON task (created_by_id)');
        $this->addSql('CREATE TABLE task_tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C0B4F048DB60186 ON task_tag (task_id)');
        $this->addSql('CREATE INDEX IDX_6C0B4F04BAD26311 ON task_tag (tag_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(125) NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, user_setting_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64949527B9E ON "user" (user_setting_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, settings JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT FK_58562B477E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE board ADD CONSTRAINT FK_58562B47120460D1 FOREIGN KEY (contributors_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE "column" ADD CONSTRAINT FK_7D53877EE7EC5785 FOREIGN KEY (board_id) REFERENCES board (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25CA372FE FOREIGN KEY (board_column_id) REFERENCES "column" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_tag ADD CONSTRAINT FK_6C0B4F048DB60186 FOREIGN KEY (task_id) REFERENCES task (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_tag ADD CONSTRAINT FK_6C0B4F04BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64949527B9E FOREIGN KEY (user_setting_id) REFERENCES user_settings (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE board DROP CONSTRAINT FK_58562B477E3C61F9');
        $this->addSql('ALTER TABLE board DROP CONSTRAINT FK_58562B47120460D1');
        $this->addSql('ALTER TABLE "column" DROP CONSTRAINT FK_7D53877EE7EC5785');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25CA372FE');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25B03A8386');
        $this->addSql('ALTER TABLE task_tag DROP CONSTRAINT FK_6C0B4F048DB60186');
        $this->addSql('ALTER TABLE task_tag DROP CONSTRAINT FK_6C0B4F04BAD26311');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64949527B9E');
        $this->addSql('DROP TABLE board');
        $this->addSql('DROP TABLE "column"');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_settings');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
